export default {
  ali: {
    token: "",
    token280: ""
  },
  quark: {
    cookie: ""
  },
  yiso: {
    url: "https://yiso.fun",
    cookie: ""
  },
  live: {
        contents: '', 
        url: [{name: '摸摸', url: 'http://api.v6x.wht.dgwht.top/text/863de13705ddfdc2/9aa228a41ac22ae6',}]
    },
  xiaoya: {
      url: ""
    },
    alist: [
        {
            name: '🐰小雅',
            server: '',
        }
    ],
    color: [        
         {
            "light": {
                "bg": "图片地址，只能图床，不能相对路径",
                "bgMask": "0x10000000",
                "primary": "0xFF6750A4",
                "onPrimary": "0xFFffffff",
                "primaryContainer": "0xFFE8DEF8",
                "onPrimaryContainer": "0xFF6750A4",
                "secondary": "0xFF6750A4",
                "onSecondary": "0xFFffffff",
                "secondaryContainer": "0xffE8DEF8",
                "onSecondaryContainer": "0xff000000",
                "tertiary": "0xFF6750A4",
                "onTertiary": "0xFFffffff",
                "tertiaryContainer": "0xFFFFFFFF",
                "onTertiaryContainer": "0xFFFFFFFF",
                "error": "0xffB3261E",
                "onError": "0xFFFFFFFF",
                "errorContainer": "0xFFE8DEF8",
                "onErrorContainer": "0xFFffffff",
                "background": "0xffEEE8F4",
                "onBackground": "0xFF000000",
                "surface": "0xffffffff",
                "onSurface": "0xff000000",
                "surfaceVariant": "0xFfE7E0EC",
                "onSurfaceVariant": "0xFF000000",
                "inverseSurface": "0x10000000",
                "onInverseSurface": "0xff000000",
                "outline": "0xFF79747E",
                "outlineVariant": "0x10000000",
                "shadow": "0x10000000",
                "scrim": "0xFF79747E",
                "inversePrimary": "0xFF79747E",
                "surfaceTint": "0xFF79747E"
            },
            "dark": {
                "bg": "https://pic.imgdb.cn/item/65a3f64f871b83018acd99ca.jpg",
                "bgMask": "0x10000000",
                "primary": "0xFF6750A4",
                "onPrimary": "0xFFffffff",
                "primaryContainer": "0xFFE8DEF8",
                "onPrimaryContainer": "0xFF6750A4",
                "secondary": "0xFF6750A4",
                "onSecondary": "0xFFffffff",
                "secondaryContainer": "0xFF6750A4",
                "onSecondaryContainer": "0xFFffffff",
                "tertiary": "0xFF6750A4",
                "onTertiary": "0xFFffffff",
                "tertiaryContainer": "0xFFFFFFFF",
                "onTertiaryContainer": "0xFFFFFFFF",
                "error": "0xffB3261E",
                "onError": "0xFFFFFFFF",
                "errorContainer": "0x10000000",
                "onErrorContainer": "0xFFffffff",
                "background": "0xFFB39DDB",
                "onBackground": "0xFFE8DEF8",
                "surface": "0xFFB39DDB",
                "onSurface": "0xFFffffff",
                "surfaceVariant": "0xFF",
                "onSurfaceVariant": "0xFFffffff",
                "inverseSurface": "0xFFE8DEF8",
                "onInverseSurface": "0xFFF1F1EA",
                "outline": "0xFF74796D",
                "outlineVariant": "0xFFC3C8BB",
                "shadow": "0xFF000000",
                "scrim": "0xFFFFFFFF",
                "inversePrimary": "0xFFFFFFFF",
                "surfaceTint": "0xFF2B6C00"
            },
        },
    ],
};
/*
                "bg": "背景图片(图床图片链接)",
                "bgMask": "背景色",
                "primary": "主色调 remarks色",
                "onPrimary": "选中的按钮字体色",
                "primaryContainer": "置顶箭头填充色",
                "onPrimaryContainer": "剪头色",
                "secondary": "观看记录左上和②填充色",
                "onSecondary": "字体色",
                "secondaryContainer": "清楚缓存+除了前三序号的填充色+左框色",
                "onSecondaryContainer": "字色",
                "tertiary": "③色",
                "onTertiary": "0xFFffffff",
                "tertiaryContainer": "0xFFFFFFFF",
                "onTertiaryContainer": "0xFFFFFFFF",
                "error": "0xffB3261E",
                "onError": "0xFFFFFFFF",
                "errorContainer": "0x10000000",
                "onErrorContainer": "0xFFffffff",
                "background": "0xFFB39DDB",
                "onBackground": "0xFFE8DEF8",
                "surface": "0xFFB39DDB",
                "onSurface": "0xFFffffff",
                "surfaceVariant": "0xFF",
                "onSurfaceVariant": "0xFFffffff",
                "inverseSurface": "0xFFE8DEF8",
                "onInverseSurface": "0xFFF1F1EA",
                "outline": "0xFF74796D",
                "outlineVariant": "0xFFC3C8BB",
                "shadow": "0xFF000000",
                "scrim": "0xFFFFFFFF",
                "inversePrimary": "0xFFFFFFFF",
                "surfaceTint": "不是自定义主题线色"
*/